### ISSUE TITLE
Results of fastsum and fast_native_sum

### ISSUE THREAD

**Issue by salabim** [chrisconlan/fast-python#2]
I have bought your book and am enjoying it very much.

However, I was very surprised to see the (minimal) difference in the performance of fast_sum and fast_native_sum. On stackoverflow.com speed improvements of 5 to 7 times are typical.
So, I decided to have a more detailed look at sum.py and when I run the tests on my machine I indeed find also a rather small improvement of fast_native_sum compared to fast_sum.
So, I was curious to see why other people have completely different observations.
With some tests, I found the cause:  your random_numeric_list function makes a list of **np.float64** numbers, So , I decided to benchmark with **float** numbers by changing your function to:
```
def random_numeric_list(n: int) -> List[float]:
    return list(float(x) for x in np.random.random(n))
```
I see that (on my machine), fast_sum is **2.3** times faster and -keep tight- fast_native_sum is **11** times faster. That makes fast_native_sum more than **7** times faster than fast_sum. And fast_native_sum is even faster than pandas_fast_sum !
That makes the whole conclusion in your book invalid, as nobody would ever use **np.float64** instead of **float** in an ordinary program.
Here's the graph I got:
[https://www.dropbox.com/s/cpm561us5hq4h36/Figure_2.png?dl=0](url)
It's also interesting to see that up to input length 1000, fast_sum is the fastest implementation! As a side remark: You never seem to pay attention to the performance with small datasets, although that can be important in practice as well.

I guess the rest of the chapter also leads to other conclusions, once you benchmark with floats.

What do you think of that?

**Comment by chrisconlan** [comment]
That's very interesting @salabim. Thanks for your research. Would you mind doing a pull request where you show your version of `sum.py` and call it `sum_alt.py` or `sum_v2.py`? If not, I can do so. 

I think your findings are important and should be addressed in a future version of the book.

**Comment by chrisconlan** [comment]
@salabim I pushed a commit with `sum_v2.py`. Thanks for your research
